=== Cortes-cmd/LenguajeDeMarcas/2ºTrimestre/Primeros_Pasos_XML/Colonias/Colonia.dtd
<!ELEMENT colonias (colonia+)>
<!ELEMENT colonia (nombre, marca, cantidad, precio?)>
<!ATTLIST colonia
          id CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT precio (#PCDATA)>

=== Cortes-cmd/LenguajeDeMarcas/2ºTrimestre/Primeros_Pasos_XML/Colonias/Colonia.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="file:/C:/Users/CampusFP/Documents/Git/MiPrimerRepo/LenguajeDeMarcas/2%C2%BATrimestre/Primeros_Pasos_XML/Colonias/Colonia.xsl"?>
<!DOCTYPE colonias SYSTEM "file:/C:/Users/CampusFP/Documents/Git/MiPrimerRepo/LenguajeDeMarcas/2%C2%BATrimestre/Primeros_Pasos_XML/Colonias/Colonia.dtd">
<colonias>
  <colonia id="1">
    <nombre>Amor amor</nombre>
    <marca>Cacharel</marca>
    <cantidad>100</cantidad>
    <precio>50</precio>
  </colonia>
    <colonia id="2">
  <nombre>Wawa</nombre>
  <marca>JeanPaul Gautier</marca>
  <cantidad>150</cantidad>
  <precio>50</precio>
  </colonia>
</colonias>
